repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: debug-statements

  # Ruff - Fast Python linter and formatter (replaces flake8, isort, black, etc.)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        exclude: ^slicer_plugin/
      # Run the formatter
      - id: ruff-format

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --python-version=3.9]
        exclude: ^(slicer_plugin|tests)/

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: [-r, --skip=B101]
        exclude: ^tests/

  # Spell checking for documentation
  - repo: https://github.com/crate-ci/typos
    rev: v1.23.2
    hooks:
      - id: typos
        exclude: \.venv/|\.git/|__pycache__/|\.egg-info/
